apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "somesecretgoeshere"
    }
# ran this:                                 kubectl apply -f secrets/secrets.yaml    
# but could have run this instead:          kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json
